DROP FUNCTION IF EXISTS Mayor;

DELIMITER $$

CREATE FUNCTION Mayor(num1 INT, num2 INT, num3 INT) RETURNS INT
BEGIN
	IF(num1>num2) THEN
		IF(num1>num3) THEN
			RETURN num1;
		ELSE
			RETURN num3;
		END IF;
	ELSEIF(num2>num3) THEN
		RETURN num2;
	ELSE
		RETURN num3;
	END IF;
END$$

DELIMITER ;
