DELIMITER $$

DROP FUNCTION IF EXISTS es_Vocal $$

CREATE FUNCTION es_Vocal(letra CHAR) RETURNS BOOLEAN
BEGIN
	IF(UPPER(letra) IN ('A','E','I','O','U')) THEN
		RETURN TRUE;
	ELSE 
		RETURN FALSE;
	END IF;
END $$

DELIMITER ;
